-- Commonwealth GPA — catalog seed
-- Run this after schema.sql. Safe to re-run (clears and reloads the catalog table).

delete from public.catalog_courses;

insert into public.catalog_courses (name, level, credits, category) values
  ('English 9', 'H', 1, 'English'),
  ('English 10', 'H', 1, 'English'),
  ('English 11', 'AP', 1, 'English'),
  ('English 12', 'APE', 1, 'English'),
  ('English 12: Reasons for Writing', 'APE', 1, 'English'),
  ('Creative Writing', 'H', 0.5, 'English'),
  ('Shakespearean Genres', 'APE', 0.5, 'English'),
  ('Ancient History', 'H', 1, 'History'),
  ('Medieval World History', 'H', 1, 'History'),
  ('United States History', 'APE', 1, 'History'),
  ('United States History since 1865', 'APE', 1, 'History'),
  ('Modern European History', 'AP', 1, 'History'),
  ('Bible-as-History/Bible-as-Bible', 'APE', 0.5, 'History'),
  ('Empires & Nationalism', 'APE', 0.5, 'History'),
  ('Mesoamerica', 'APE', 0.5, 'History'),
  ('The World Since 1945', 'APE', 0.5, 'History'),
  ('Economics', 'AP', 1, 'History'),
  ('U.S. Politics in the 21st Century', 'APE', 1, 'History'),
  ('The City in Film', 'APE', 0.5, 'History'),
  ('Jazz Theory 1', 'H', 0.5, 'Arts'),
  ('Jazz Theory 2', 'H', 0.5, 'Arts'),
  ('Music Theory 1', 'H', 0.5, 'Arts'),
  ('Music Theory 2', 'APE', 0.5, 'Arts'),
  ('Conducting and Advanced Music Theory/Composition', 'APE', 0.5, 'Arts'),
  ('French 1', 'Regular', 1, 'Language'),
  ('French 2', 'H', 1, 'Language'),
  ('French 3', 'AP', 1, 'Language'),
  ('French 4 Conversation', 'APE', 0.5, 'Language'),
  ('French 4 Literature', 'APE', 0.5, 'Language'),
  ('Spanish 1', 'H', 1, 'Language'),
  ('Spanish 2', 'H', 1, 'Language'),
  ('Spanish 3', 'APE', 1, 'Language'),
  ('Spanish 4 Conversation', 'APE', 0.5, 'Language'),
  ('Spanish 4 Literature', 'APE', 0.5, 'Language'),
  ('Latin 1', 'Regular', 1, 'Language'),
  ('Latin 2', 'H', 1, 'Language'),
  ('Latin 3', 'AP', 1, 'Language'),
  ('Latin 4', 'Regular', 1, 'Language'),
  ('Latin 5', 'AP', 1, 'Language'),
  ('Mandarin 1', 'H', 1, 'Language'),
  ('Mandarin 2', 'H', 1, 'Language'),
  ('Mandarin 3', 'H', 1, 'Language'),
  ('Mandarin 4', 'H', 1, 'Language'),
  ('Mandarin 5', 'Regular', 1, 'Language'),
  ('Mandarin 6', 'Regular', 1, 'Language'),
  ('Mandarin 7', 'Regular', 1, 'Language'),
  ('Mandarin 8', 'APE', 1, 'Language'),
  ('Biology 1', 'H', 1, 'Science'),
  ('Biology 2', 'AP', 1, 'Science'),
  ('Neuroscience', 'APE', 0.5, 'Science'),
  ('Chemistry 1 Advanced', 'H', 1, 'Science'),
  ('Chemistry 1', 'H', 1, 'Science'),
  ('Chemistry 2', 'AP', 1, 'Science'),
  ('Physics 1 Advanced', 'APE', 1, 'Science'),
  ('Physics 1 Accelerated', 'APE', 1, 'Science'),
  ('Physics 1', 'H', 1, 'Science'),
  ('Physics 2', 'APE', 1, 'Science'),
  ('Astronomy', 'APE', 0.5, 'Science'),
  ('Geometry Advanced', 'H', 1, 'Mathematics'),
  ('Geometry', 'H', 1, 'Mathematics'),
  ('Intermediate Algebra', 'H', 1, 'Mathematics'),
  ('Algebra 2/Precalculus Advanced', 'H', 1, 'Mathematics'),
  ('Algebra 2/Precalculus', 'H', 1, 'Mathematics'),
  ('Calculus 1 Advanced', 'AP', 1, 'Mathematics'),
  ('Calculus 1 Accelerated', 'AP', 1, 'Mathematics'),
  ('Calculus 1', 'H', 1, 'Mathematics'),
  ('Calculus 2', 'AP', 1, 'Mathematics'),
  ('Multivariable Calculus', 'APE', 1, 'Mathematics'),
  ('Theoretical Calculus', 'APE', 1, 'Mathematics'),
  ('Statistics and Applied Mathematics for Social Choice', 'H', 1, 'Mathematics'),
  ('Proofs and Problem Solving', 'APE', 0.5, 'Mathematics'),
  ('Abstract Algebra: Groups, Rings, Fields', 'APE', 0.5, 'Mathematics'),
  ('Differential Equations', 'APE', 0.5, 'Mathematics'),
  ('Computer Programming Essentials (CS 1)', 'H', 0.5, 'Mathematics'),
  ('Designing Programs (CS 2)', 'H', 0.5, 'Mathematics'),
  ('Designing with Classes (CS 3)', 'APE', 0.5, 'Mathematics'),
  ('Computer Science Theory (CS4/CS5)', 'APE', 0.5, 'Mathematics'),
  ('Beginning Acting', 'Regular', 0.5, 'Arts'),
  ('Advancing Acting', 'Regular', 0.5, 'Arts'),
  ('Chorus', 'Regular', 0.5, 'Arts'),
  ('Chorale', 'H', 0.5, 'Arts'),
  ('Orchestra', 'Regular', 0.5, 'Arts'),
  ('Chamber Music', 'Regular', 0.5, 'Arts'),
  ('Jazz Ensemble', 'Regular', 0.5, 'Arts'),
  ('Beginning Photography', 'Regular', 0.5, 'Arts'),
  ('Advancing Photography', 'Regular', 0.5, 'Arts'),
  ('Drawing and Painting 1', 'Regular', 0.5, 'Arts'),
  ('Advancing Drawing and Painting', 'Regular', 0.5, 'Arts'),
  ('Sequential Arts', 'Regular', 0.5, 'Arts'),
  ('Life Drawing 1', 'Regular', 0.5, 'Arts'),
  ('Advancing Life Drawing', 'Regular', 0.5, 'Arts'),
  ('Beginning Printmaking', 'Regular', 0.5, 'Arts'),
  ('Advancing Printmaking', 'Regular', 0.5, 'Arts'),
  ('Beginning Ceramics', 'Regular', 0.5, 'Arts'),
  ('Advancing Ceramics', 'Regular', 0.5, 'Arts'),
  ('Sculpture', 'Regular', 0.5, 'Arts'),
  ('Ninth-Grade Seminar', 'Regular', 0.5, 'History'),
  ('The Purposes of Education', 'Regular', 0.25, 'History'),
  ('College and Senior Seminar', 'Regular', 0, 'History'),
  ('Capstone Project', 'Regular', 0.5, 'History');
